eureka:
  instance:
    hostname: spring-cloud-config
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${REGISTER_SERVER_URL:http://localhost:8761/eureka/}
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: ${CONFIG_URL:https://github.com/snipking/spring-cloud-config-repo.git}
          searchPaths: '{profile}'
        bootstrap: true
  profiles:
    active: default
server:
  port: ${PORT:8888}
