spring:
  application:
    name: spring-cloud-register
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0

server:
  port: ${PORT:8761}
